### ISSUE TITLE
Allow template evaluation in task variables

### ISSUE THREAD

**Issue by smyrman** [go-task/task#40]
Issue #38 is about allowing a variable to be passed onto a sub-task or dependency. The chosen way to handle it, at least initially, was to allow for template variables to be evaluated when passing on the vars. See #39.

However, it might make sense to allow _global_ variables and task _parameters_ to be evaluated in a task's local vars and env section as well. The example below is maybe not the best use-case, but it should illustrate what I mean:

```yaml
# Taskvars.yml
GOOS: $go env GOOS
GOARCH: $go env GOARCH
```

```yaml
# Taskfile.yml
default:
  vars:
    TARGET_DIR: "build/{{.GOOS}}_{{.GOARCH}}"
  env:
    GOOS: "{{.GOOS}}"
    GOARCH: "{{.GOARCH}}"
  cmds:
   - mkdir -p "{{.TARGET_DIR}}"
   - go build -o '{{.TARGET_DIR}}/myapp' .

cross-compile:
  deps:
    - task: default
      vars: {GOOS: linux}
    - task: default
      vars: {GOOS: windows, GOARCH: 386}
    - task: default
      vars: {GOOS: windows, GOARCH: amd64}
    - task: default
      vars: {GOOS: darwin}
```

Another reason for adding this feature is to make the behaviour more consistent, and to allow for easier documentation of the detailed behaviour. E.g.:
- task scoped variables and env have access to global variables and environment variables, as well as passed in task override variables.
- variables set when calling a task, has access to all of the above, pluss any variables or environemnt variables set on the task.

**Comment by andreynering** [comment]
Working on master branch. I'll keep this open until it can be tested.

**Comment by smyrman** [comment]
Cool, that's fast!

**Comment by andreynering** [comment]
I'm closing this by now. If any issue rises, it can be reopened.

**Comment by smyrman** [comment]
Dosn't seam to work...

```yaml
# component-go-bindata is a reusable task to buils go binary assets from web
# assets.
component-go-bindata:
  vars:
    COMPONENT: null       # component to build bindata for (configurator, web)
    WEB_TARGET_SUFFIX: "" # suffix for webpack target folder name
    WEB_BUILD_OPTIONS: "" # prefix for npm build command
    TARGET: "{{.BUILD_DIR_ANY}}/web/{{.COMPONENT}}{{.WEB_TARGET_SUFFIX}}"
  deps:
    - go-bindata-assetfs
  dir: "cmd/{{.COMPONENT}}"
  cmds:
    - echo "{{.BUILD_DIR_ANY}}/web/{{.COMPONENT}}{{.WEB_TARGET_SUFFIX}}"
    - echo "{{.TARGET}}"
```

Gives me:
```sh
...
echo "/Users/smyrman/.local/src/github.com/searis/synergylog/build/any/web/client-boat"
/Users/smyrman/.local/src/github.com/searis/synergylog/build/any/web/client-boat
echo "{{.BUILD_DIR_ANY}}/web/{{.COMPONENT}}{{.WEB_TARGET_SUFFIX}}"
{{.BUILD_DIR_ANY}}/web/{{.COMPONENT}}{{.WEB_TARGET_SUFFIX}}

```

**Comment by andreynering** [comment]
@smyrman Did you check you are using current `master` branch?

I did a try and seems to be working for me. (Unless I miss the point, I'll wait for the reproduce Taskfile).

**Comment by smyrman** [comment]
It's a valid question, because I managed to mess this up before I reported #43, although then the issue was still on master.

I had master checked out, but I must have failed to correctly reinstall cmd/task, because after reinstalling I find now that it _almost_ works:

```sh
echo "/Users/smyrman/.local/src/(...)/build/any/web/client-boat"
/Users/smyrman/.local/src/github.com/(...)/build/any/web/client-boat
echo "<no value>/web/client-boat"
<no value>/web/client-boat
```

What is happening here, is that the template evaluation in VARS appears to not have access to the global variables set in `Taskvars.yml`, while the one in the cmds section do.

**Comment by smyrman** [comment]
I was thinking btw, and I will raise a new issue about that, that it would be nice with some refactoring to how variables flow through the program to avoid this kind of mistakes. I will raise one, and hear what you think.

**Comment by smyrman** [comment]
I am on commit a586fef414f2a8a930bf7d9126812ee3d1b19c12 btw.

**Comment by andreynering** [comment]
I'll check Taskvars.yml not loading when have a little of time

**Comment by smyrman** [comment]
thx. Sorry for the poor bug-report this time.

**Comment by andreynering** [comment]
Should be fixed on master

**Comment by smyrman** [comment]
I am afraid this is still broken, and so is your test. Your test only works because the "PORTUGUESE" variable has the same name (nad content) in `Taskfile.yml` and `Taskvars.yml`. When you run your cmd, you are actually accessing the one in `Taskvars.yml` which _overrides_ the one in the `Taskfile.yml`

Here is a test to reproduce it:
```yaml
default:
  vars:
    VAR: "{{.TAVAR}}" # fails
    SVAR: "{{.SVAR}} + 1" # igonred, SVAR in Taskvars overides this.
  cmds:
    - "echo 'default via cmds: TVAR={{.TVAR}}'"
    - "echo 'default via vars: VAR={{.VAR}}'"
    - "echo 'default via vars: SVAR={{.SVAR}}'"
```

Taskvars.yml:
```yaml
TVAR: 42
SVAR: 32
```

Run:
```
$ task
task: No argument given, trying default task
echo 'default via cmds: TVAR=42'
default via cmds: TVAR=42
echo 'default via vars: VAR=<no value>'
default via vars: VAR=<no value>
echo 'default via vars: SVAR=32'
default via vars: SVAR=32
```

**Comment by smyrman** [comment]
Commit 72250b32d3afaebe5d0aef9ad7fb4d9cc3aa1ce4 changes the behavior again:
```
$ task            
task: No argument given, trying default task
echo 'default via cmds: TVAR=42'
default via cmds: TVAR=42
echo 'default via vars: VAR={{.TVAR}}'
default via vars: VAR={{.TVAR}}
echo 'default via vars: SVAR=32'
default via vars: SVAR=32
```
