### ISSUE TITLE
Seg fault on empty command

### ISSUE THREAD

**Issue by Tiksagol** [go-task/task#534]
- Task version: 3.0.0
- Operating System: Linux (Ubuntu 18.04.04)

### Example Taskfile showing the issue

```version: '3'
tasks:
  hello:
    desc: 'hi'
    cmds:
      - echo "hi"
      -
```

When running `task -l` it fails with:
```
> task -t test_task.yml -l
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x67b381]

goroutine 1 [running]:
github.com/go-task/task/v3.(*Executor).CompiledTask(0xc00009a2c0, 0xc000016b50, 0x5, 0x0, 0x0, 0x0, 0x4008000000000000)
        /home/runner/work/task/task/variables.go:78 +0x1101
github.com/go-task/task/v3.(*Executor).tasksWithDesc(0xc00009a2c0, 0xc00000e0e0, 0x0, 0x1)
        /home/runner/work/task/task/help.go:33 +0x152
github.com/go-task/task/v3.(*Executor).PrintTasksHelp(0xc00009a2c0)
        /home/runner/work/task/task/help.go:14 +0x40
main.main()
        /home/runner/work/task/task/cmd/task/task.go:152 +0xdbc
```

**Comment by SwitchedToGitlab** [comment]
As of version 3.6.0 this issue has been resolved. @Tiksagol please update your ```task``` binary to the latest version and try again, and thank you for your bug report.

@andreynering this issue can be marked as CLOSED as FIXED in the latest version. 

```yaml
☢  cat -pp Taskfile.yml 
tasks:
  hello:
    desc: 'hi'
    cmds:
      - echo "hi"
      -python3/sandbox on  FEATURE/USE_LANG_IMAGE [!?] 
```

```bash
task: Could not parse taskfile version "": strconv.ParseFloat: parsing "": invalid syntax
```

**Comment by andreynering** [comment]
Yep, closing as fixed.

If you are able to reproduce this on the current version, let us know and we'll reopen the issue.

**Comment by Tiksagol** [comment]
Hi,

Still happens with go-task 3.7.0 when '**version**' is declared:
``` > cat Taskfile.yml 
version: '3'

tasks:
  hi:
    cmds:
      - echo
      -

> task --version
Task version: v3.7.0 (h1:8dDFv12/Lxi6PHkYNIIm7N6v6oRGxePpLK67LuMh/Rs=)

> task hi
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6d039c]

goroutine 1 [running]:
github.com/go-task/task/v3.(*Executor).compiledTask(0xc0000692b0, 0x7fffffffe72f, 0x2, 0x0, 0xc00015bc01, 0xc000080000, 0x0, 0x722880)
        /home/runner/go/pkg/mod/github.com/go-task/task/v3@v3.7.0/variables.go:96 +0x11dc
github.com/go-task/task/v3.(*Executor).CompiledTask(...)
        /home/runner/go/pkg/mod/github.com/go-task/task/v3@v3.7.0/variables.go:16
github.com/go-task/task/v3.(*Executor).RunTask(0xc0000692b0, 0x7c2de0, 0xc00018c040, 0x7fffffffe72f, 0x2, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/go-task/task/v3@v3.7.0/task.go:301 +0x8c
github.com/go-task/task/v3.(*Executor).Run(0xc0000692b0, 0x7c2de0, 0xc00018c000, 0xc00000c5a0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/go-task/task/v3@v3.7.0/task.go:98 +0x39a
main.main()
        /home/runner/go/pkg/mod/github.com/go-task/task/v3@v3.7.0/cmd/task/task.go:188 +0xe88
